# Generated by Django 3.0.4 on 2020-03-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите Ваше имя', max_length=100, verbose_name='Имя пользователя')),
                ('email', models.EmailField(help_text='Введите ваш email', max_length=100, verbose_name='Email пользователя')),
                ('content', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение пользователя')),
            ],
        ),
    ]
