# Generated by Django 3.0.4 on 2020-03-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200308_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_two',
            field=models.TextField(verbose_name='Второй текст поста'),
        ),
    ]
