# Generated by Django 3.0.4 on 2020-03-12 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data_one',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения товара'),
        ),
    ]
