# Generated by Django 3.0.4 on 2020-03-10 03:43

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactures', to='products.Category')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Произовдители',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Имя Товара')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='фото продукта', width_field='width_field')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location, verbose_name='фото продукта2')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location, verbose_name='фото продукта3')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location, verbose_name='фото продукта4')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location, verbose_name='фото продукта5')),
                ('image_six', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, verbose_name='фото продукта6', width_field='width_field')),
                ('image_seven', models.ImageField(blank=True, null=True, upload_to=products.models.upload_location, verbose_name='фото продукта7')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, db_index=True)),
                ('fuel', models.CharField(blank=True, max_length=50, verbose_name='Топливо')),
                ('rated_power', models.FloatField(blank=True, null=True, verbose_name='Номинальная мощь')),
                ('max_power', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Максимальная мощь')),
                ('launch_sys', models.CharField(blank=True, max_length=50, verbose_name='Система пуска')),
                ('engine', models.CharField(blank=True, max_length=50, verbose_name='Тип двигателя')),
                ('weight', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Вес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stok', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Опубликовано')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Manufacturer')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить на экран?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликован')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Product', verbose_name='Обьявление')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
