# Generated by Django 3.0.4 on 2020-03-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.TextField(blank=True, max_length=50, verbose_name='Страна производителя'),
        ),
    ]
