# Generated by Django 3.0.4 on 2020-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_manufacturer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Страна производителя'),
        ),
    ]
