# Generated by Django 3.0.4 on 2020-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200311_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производителя'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производителя'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производителя'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='title_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='content_uk',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='product',
            name='launch_sys_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Система пуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='launch_sys_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Система пуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='launch_sys_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Система пуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Имя Товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Имя Товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Имя Товара'),
        ),
    ]
