# Generated by Django 3.0.4 on 2020-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200311_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('a', 'Аналог'), ('o', 'Оригинал')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
